name: Midnight Analytics
favicon: null
layout_spectrum: 0.4814581316895783
typography_spectrum: 0.5294097708538175
title: Midnight Analytics
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.28092333814129233
  lightness: 0.030605288920924067
  saturation: 0.6848004749044776
  rhythmicContrast: 0.9378964847419411
purpose: []
