typography_spectrum: 0.5294097708538175
color:
  brandColors:
    - '#ffffff'
    - '#231f20'
    - '#8655a1'
    - '#1074b6'
    - '#ad8bb8'
  brandStrength: 0.28092333814129233
  lightness: 0.030605288920924067
  saturation: 0.6848004749044776
  rhythmicContrast: 0.9378964847419411
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.4814581316895783
analytics:
  google: null
  facebook: null
  twitter: null
name: Midnight Analytics
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Midnight Analytics
description: Data Visualizations
purpose: []
